spring:

  application:
    name: WebApp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/admindb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  docker:
    compose:
      enabled: false

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized